export const constants = {
    AUTH: {
        AUTH_TITLE: "Авторизация",
        AUTH_LABEL_SELECT_ROLE: "Войти как",
        AUTH_LOGIN: "Имя пользователя",
        AUTH_PASS: "Пароль",
        AUTH_PASS_PLACEHOLDER: "Введите пароль",
        AUTH_FORGET_PASS: "Забыли пароль?",
        AUTH_REMEMBER_ME: "Запомнить меня",
        AUTH_ENTER_BTN: "Войти",
        AUTH_ENTER_BTN_LOADING: "Загрузка...",
        AUTH_ENTER_LINK_GOSUSLUGI: "Войти через ЕСИА",
        AUTH_TITLE_LOGO_BLOCK: "Панель управления системой электронных голосований",
        AUTH_QUESTION_ACCOUNT: "Еще нет аккаунта?",
        AUTH_REG_BTN: "Зарегистрироваться",
        AUTH_ERROR_MESSAGE: "Неверно введено имя пользователя или пароль",
        AUTH_ERROR_MESSAGE_REQUIRED: "Заполните все обязательные поля",
        AUTH_ROLE_ADMIN: 'Секретарь',
        AUTH_ROLE_OBSERVER: 'Наблюдатель',
        AUTH_ROLE_COUNTER: 'Член счетной комиссии'
    },
    HEADER: {
        HEADER_ORG: "Организации",
        HEADER_MAIN: "Главная",
        HEADER_USERS: "Пользователи",
        HEADER_VOTE: "Голосования",
        HEADER_GROUP_USERS: "Группы пользователей",
        HEADER_USERS_LIST: "Список пользователей",
        HEADER_LIST_VOTES: "Список голосований",
        HEADER_TEMPLATE_VOTES: "Шаблоны голосований",
        HEADER_ADD_BTN: "Добавить",
        HEADER_ADD_ORG: "Организацию",
        HEADER_ADD_VOTE: "Голосование",
        HEADER_ADD_TEMPLATE_VOTE: "Шаблон голосования",
        HEADER_ADD_GROUP_USERS: "Группу пользователей",
        HEADER_MYPROFILE_MODAL: "Мой профиль",
        HEADER_MYPROFILE_MODAI_EXIT: "Выйти",
        HEADER_BURGER_ADD_BTN: "Добавить",
        HEADER_BURGER_ORG: "Организации",
        HEADER_BURGER_ADD_ORG: "Организацию",
        HEADER_BURGER_POLITIC: "Политика конфидициальности",
        HEADER_BURGER_EXIT: "Выйти"
    },
    FOOTER: {
        FOOTER_COPI_INFO_PART1: "Система",
        FOOTER_COPI_INFO_PART2: "разработана Центром",
        FOOTER_COPI_INFO_PART3: "технологий распределенных",
        FOOTER_COPI_INFO_PART4: "реестров СПбГУ.",
        FOOTER_COPI_INFO_PART5: "Все права защищены.",
        FOOTER_MAP_SITE: "Карта сайта",
        FOOTER_MAIN_PAGE: "Главная",
        FOOTER_VOTES: "Голосования",
        FOOTER_LIST_VOTES: "Список голосований",
        FOOTER_TEMPLATE_VOTES: "Шаблоны голосований",
        FOOTER_USERS: "Пользователи",
        FOOTER_GROUP_USERS: "Группы пользователей",
        FOOTER_LIST_USERS: "Список пользователей",
        FOOTER_ORG: "Организации",
        FOOTER_MYPROFILE: "Мой профиль",
        FOOTER_SETTINGS: "Настройки",
        FOOTER_LANG: "Язык",
        FOOTER_SELECT_LANG_RU: "Русский",
        FOOTER_SELECT_LANG_EN: "Английский",
        FOOTER_SIZE_FONT: "Размер шрифта",
        FOOTER_SELECT_SIZE: "Стандартный",
        FOOTER_TIME_ZONE: "Часовой пояс",
        FOOTER_SELECT_TIME_ZONE: "GMT+03:00",
        FOOTER_SUPPORT: "Поддержка",
        FOOTER_POLITIC: "Политика конфиденциальности",
        FOOTER_MAIL_SUPPORT: "support@dltc.spbu.ru"
    },
    GENERAL_TITLE: {
        GENERAL_TITLE_TITLENAME_ORG: "Список организаций",
        GENERAL_TITLE_TITLENAME_VOTES: "Голосования",
        GENERAL_TITLE_TITLENAME_DETAILS_VOTE: "Детали голосования",
        GENERAL_TITLE_TITLENAME_GROUP_USER: "Группы пользователей",
        GENERAL_TITLE_TITLENAME_TEMPLATES_VOTE: "Шаблоны голосований",
        GENERAL_TITLE_ADD_ORG: "Добавить организацию",
        GENERAL_TITLE_TITLENAME_ADD_VOTE: "Добавление нового голосования",
        GENERAL_TITLE_TITLENAME_ADD_ORG: "Добавление новой организации",
        GENERAL_TITLE_TITLENAME_ADD_GROUP_USERS: "Добавление группы пользователей",
        GENERAL_TITLE_TITLENAME_ADD_TEMPLATES_VOTE: "Добавление нового шаблона",
        GENERAL_TITLE_TITLENAME_LIST_USERS: "Список пользователей",
        GENERAL_TITLE_TITLENAME_PROFILE: "Профиль пользователя",
        GENERAL_TITLE_FIRTSLETTER: "АдминистраторКриптовече",
        GENERAL_TITLE_SECONDLETTER_ORG: "Организации",
        GENERAL_TITLE_SECONDLETTER_ORG_MANY: "Организация",
        GENERAL_TITLE_SECONDLETTER_GROUP_USERS: "Группы пользователей",
        GENERAL_TITLE_SECONDLETTER_LIST_USERS: "Список пользователей",
        GENERAL_TITLE_SECONDLETTER_VOTES: "Голосования",
        GENERAL_TITLE_SECONDLETTER_DETAILS_VOTE: "Детали голосования",
        GENERAL_TITLE_SECONDLETTER_ADD_VOTE: "Добавить голосование",
        GENERAL_TITLE_SECONDLETTER_TEMPLATES_VOTE: "Шаблоны голосований",
        GENERAL_TITLE_SECONDLETTER_ADD_TEMPLATES_VOTE: "Добавить шаблон"
    },
    PAGINATION: {
        PAGINATION_SHOW_LABEL: "Показать",
        PAGINATION_PAGE_FROM_PAGE: "из",
        PAGINATION_SEARCH: "Поиск"
    },
    ORGANIZATIONS_LIST: {
        ORGANIZATIONS_LIST_NAME_ORG: "Название организации",
        ORGANIZATIONS_LIST_SECRETARY: "Секретари",
        ORGANIZATIONS_LIST_GROUP_USERS: "Группы пользователей",
        ORGANIZATIONS_LIST_VOTES: "Голосования",
        ORGANIZATIONS_LIST_ACTIVE_VOTES: "Активные голосования",
        ORGANIZATIONS_LIST_TEMPLATES: "Шаблоны",
        ORGANIZATIONS_LIST_ACTIONS: "Действия",
        ORGANIZATIONS_LIST_EDIT_BTN: "РЕДАКТИРОВАТЬ",
        ORGANIZATIONS_LIST_EDIT_BTN_MOBILE: "Редактировать"
    },
    ADD_NEW_ORG: {
        ADD_NEW_ORG_NAME_ORG: "Название организации",
        ADD_NEW_ORG_PLACEHOLDER_NAME: "Введите название организации",
        ADD_NEW_ORG_IMPORT_EXCEL_BTN: "Импорт пользователей из Excel",
        ADD_NEW_ORG_ADD_USERS_MAIL_BTN: "Добавить пользователей по E-mail",
        ADD_NEW_ORG_ADD_USERS_MAIL_BTN_MOBILE: "Добавить пользователей",
        ADD_NEW_ORG_MAIL_ADDRESS_USERS: "Почтовые адреса пользователей",
        ADD_NEW_ORG_DOWNLOAD_FILE_LABEL: "Загрузить xlsx документ со списком пользователей",
        ADD_NEW_ORG_LOAD_BTN: "Загрузить",
        ADD_NEW_ORG_SUCCESS_INFO: "Файл успешно загружен",
        ADD_NEW_ORG_MAIL_ADDRESS_USERS_RULE: "(по одному на каждую строчку для каждого пользователя)",
        ADD_NEW_ORG_SEARCH_USERS_BASE_BTN: "Найти в базе пользователей",
        ADD_NEW_ORG_E_MAIL_SUPPORT: "E-mail поддержки",
        ADD_NEW_ORG_E_MAIL_SUPPORT_PLACEHOLDER: "Введите E-mail поддержки",
        ADD_NEW_ORG_NOTE: "Примечание",
        ADD_NEW_ORG_INPUT_NOTE: "Введите примечание",
        ADD_NEW_ORG_SAVE_BTN: "Сохранить",
        ADD_NEW_ORG_SUPERUSER: "Суперпользователь",
        ADD_NEW_ORG_DELETE_BTN: "УДАЛИТЬ",
        ADD_NEW_ORG_DELETE_BTN_PROCESS: "УДАЛЕНИЕ...",
        ADD_NEW_ORG_DELETE_BTN_MOBILE: "Удалить",
        ADD_NEW_ORG_DELETE_BTN_MOBILE_PROCESS: "Удаление...",
        ADD_NEW_ORG_BLOCK_BTN: "Заблокировать",
        ADD_NEW_ORG_UNBLOCK_BTN: "Разблокировать",
        ADD_NEW_ORG_SHOW_MORE_BTN: "ПОКАЗАТЬ ЕЩЁ",
        ADD_NEW_ORG_SELECT_FILE: "Выберите файл",
        ADD_NEW_ORG_NO_USERS: "Список пользователей пуст",
        ADD_NEW_ORG_DEFAULT_FIRST_NAME: "Без",
        ADD_NEW_ORG_DEFAULT_LAST_NAME: "Пользователь",
        ADD_NEW_ORG_DEFAULT_SECOND_NAME: "Имени",
        ADD_NEW_ORG_EMAIL_ERROR: "Введён некорректный формат почты",
        ADD_NEW_ORG_SUPPORT_EMAIL_ERROR: "Некорректный E-mail поддержки",
        ADD_NEW_ORG_SAVE_ERROR: "Название организации не может быть пустым",
        ADD_NEW_ORG_FAILURE_ERROR: "Что-то пошло не так..."
    },
    ADD_NEW_GROUP_USERS: {
        ADD_NEW_GROUP_USERS_SELECT_ORG: "Выбор организации",
        ADD_NEW_GROUP_USERS_ORG: "Организация",
        ADD_NEW_GROUP_NEXT_BTN: "Далее",
        ADD_NEW_GROUP_USERS_NAME_GROUP_USERS: "Название группы пользователей",
        ADD_NEW_GROUP_USERS_PLACEHOLDER_NAME: "Введите название группы",
        ADD_NEW_GROUP_USERS_IMPORT_EXCEL_BTN: "Импорт пользователей из Excel",
        ADD_NEW_GROUP_USERS_ADD_GROUP_BTN: "Добавить в группу пользователей",
        ADD_NEW_GROUP_MAIL_ADDRESS_USERS: "Почтовые адреса пользователей",
        ADD_NEW_GROUP_MAIL_ADDRESS_USERS_RULE: "(по одному на каждую строчку для каждого пользователя)",
        ADD_NEW_GROUP_SEARCH_USERS_BASE_BTN: "Найти в базе пользователей",
        ADD_NEW_GROUP_USERS_DELETE_BTN: "УДАЛИТЬ",
        ADD_NEW_GROUP_USERS_SAVE_BTN: "Сохранить",
        ADD_NEW_GROUP_USERS_SHOW_MORE_BTN: "ПОКАЗАТЬ ЕЩЁ",
        ADD_NEW_GROUP_USERS_LOAD_BTN: "Загрузить",
        ADD_NEW_GROUP_USERS_DOWNLOAD_FILE_LABEL: "Загрузить xls/xlsx документ со списком пользователей",
        ADD_NEW_GROUP_SUCCESS_INFO: "Файл успешно загружен"
    },
    PROFILE_USER: {
        PROFILE_USER_EDIT_BTN: "Редактировать профиль",
        PROFILE_USER_ORG_GROUP_USERS: "Организации и группы пользователя",
        PROFILE_USER_ACTIVITY_IN_USER_GROUPS: "Членство в группах пользователей",
        PROFILE_USER_VOTES: "Голосования",
        PROFILE_USER_STATUS_VOTING: "Голосующий",
        PROFILE_USER_STATUS_OBSERVER: "Наблюдатель",
        PROFILE_USER_STATUS_SECRETARY: "Секретарь",
        PROFILE_USER_SHOW_ALL: "ПОКАЗАТЬ ПОЛНОСТЬЮ",
        PROFILE_USER_SAVE_BTN: "Сохранить изменения",
        PROFILE_USER_CHANGE_PERSONAL_DATA: "Изменить личные данные",
        PROFILE_USER_SURNAME: "Фамилия",
        PROFILE_USER_NAME: "Имя",
        PROFILE_USER_MIDDLE_NAME: "Отчество",
        PROFILE_USER_CHANGE_TIMEZONE: "Изменить часовой пояс",
        PROFILE_USER_CHANGE_PASS: "Изменить пароль",
        PROFILE_USER_PASS: "Пароль",
        PROFILE_USER_NEW_PASS: "Новый пароль",
        PROFILE_USER_REPEAT_PASS: "Повторите новый пароль"
    },
    GROUP_USERS: {
        GROUP_USERS_NAME_GROUP_USERS: "Название группы пользователей",
        GROUP_USERS_MEMBERS: "Участники",
        GROUP_USERS_ACTIONS: "Действия",
        GROUP_USERS_SHOW_GROUP: "ПОСМОТРЕТЬ ГРУППУ",
        GROUP_USERS_EDIT_BTN: "РЕДАКТИРОВАТЬ",
        GROUP_USERS_BLOCK_BTN: "ЗАБЛОКИРОВАТЬ",
        GROUP_USERS_UNBLOCK_BTN: "РАЗБЛОКИРОВАТЬ",
        GROUP_USERS_DELETE_BTN: "УДАЛИТЬ",
        GROUP_USERS_ADD_USER_BTN_MOBILE: "Добавить пользователей",
        GROUP_USERS_SELECT_BTN_SELECT: "Выбрать",
        GROUP_USERS_MODAL_SELECTED: "Выбрано",
        GROUP_USERS_MODAL_NUMBER_GROUP: "группа",
        GROUP_USERS_MODAL_NUMBER_GROUPS: "группы",
        GROUP_USERS_MODAL_NUMBER_SEVERAL_GROUP: "групп",
        GROUP_USERS_MODAL_CANCEL: "Отмена",
        GROUP_USERS_MODAL_DELETE_SELECTED: "Удалить выбранное"
    },
    LIST_USERS: {
        LIST_USERS_TABLE_EMAIL: "E-mail",
        LIST_USERS_USERNAME: "ФИО",
        LIST_USERS_ACTIONS: "Действия",
        LIST_USERS_WATCH_PROFILE: "ПОСМОТРЕТЬ ПРОФИЛЬ",
        LIST_USERS_SHOW_MORE: "ПОКАЗАТЬ ЕЩЁ"
    },
    FILTER_SORT_BLOCK: {
        FILTER_SORT_BLOCK_FILTERS: "Фильтры",
        FILTER_SORT_BLOCK_SORTING: "Сортировка",
        FILTER_SORT_BLOCK_BY_VOTING_STATUS: "По статусу голосования",
        FILTER_SORT_BLOCK_STATUS_VOTING: "Статус голосования",
        FILTER_SORT_BLOCK_BY_VOTING_TYPE: "По типу голосования",
        FILTER_SORT_BLOCK_TYPE_VOTING: "Тип голосования",
        FILTER_SORT_BLOCK_BY_REG_START_DATE: "По дате начала регистрации",
        FILTER_SORT_BLOCK_REG_START_DATE: "Дата начала регистрации",
        FILTER_SORT_BLOCK_BY_VOTE_START_DATE: "По дате начала голосования",
        FILTER_SORT_BLOCK_VOTE_START_DATE: "Дата начала голосования",
        FILTER_SORT_BLOCK_FROM: "c",
        FILTER_SORT_BLOCK_TO: "по",
        FILTER_SORT_BLOCK_VOTING_IN_PROGRESS: "Идет голосование",
        FILTER_SORT_BLOCK_REG_IN_PROGRESS: "Идет регистрация",
        FILTER_SORT_BLOCK_VOTING_AND_REG: "Регистрация и голосование",
        FILTER_SORT_BLOCK_WAITING_VOTE: "Ожидание голосования",
        FILTER_SORT_BLOCK_WAITING_REG: "Ожидание регистрации",
        FILTER_SORT_BLOCK_VOTE_END: "Голосование завершено",
        FILTER_SORT_BLOCK_QUORUM_NOT_REACHED: "Кворум не достигнут",
        FILTER_SORT_BLOCK_OPEN: "Открытое",
        FILTER_SORT_BLOCK_CLOSE: "Тайное",
        FILTER_SORT_BLOCK_APPLY_FILTER: "Применить фильтр",
        FILTER_SORT_BLOCK_RESET_FILTERS: "Сбросить все фильтры",
        FILTER_SORT_BLOCK_EVENT_NAME: "Названию события",
        FILTER_SORT_BLOCK_ORG_NAME: "Названию организации",
        FILTER_SORT_BLOCK_TIME_START_REG: "Времени начала регистрации",
        FILTER_SORT_BLOCK_TIME_START_VOTE: "Времени начала голосования",
        FILTER_SORT_BLOCK_TIME_END_REG: "Времени окончания регистрации",
        FILTER_SORT_BLOCK_TIME_END_VOTE: "Времени окончания голосования",
        FILTER_SORT_BLOCK_ALT_BUTTON_CLOSE_WINDOW: "кнопка-крестик-закрыть окно",
        FILTER_SORT_BLOCK_ALT_BUTTON_SORT_LOW: "иконка сортировки на убывание",
        FILTER_SORT_BLOCK_ALT_BUTTON_ALT_SORT_UP: "иконка сортировки на увеличение",
        FILTER_SORT_BLOCK_ALT_RED_CIRCLE: "красная точка",
        FILTER_SORT_BLOCK_ALT_ICON_FILTER: "иконка фильтр",
        FILTER_SORT_BLOCK_ALT_ICON_SORT: "иконка сортировка"
    },
    VOTES_PAGE: {
        VOTES_PAGE_SWITCH_ACTIVE_BTN: "Активные",
        VOTES_PAGE_SWITCH_ACTIVE_BTN_MOBILE: "голосования",
        VOTES_PAGE_SWITCH_ARCHIVE_BTN: "Архивные",
        VOTES_PAGE_SWITCH_ARCHIVE_BTN_MOBILE: "голосования",
        VOTES_PAGE_SHOW_MORE_BTN: "ПОКАЗАТЬ ЕЩЁ",
        VOTES_PAGE_SHOW_INFO_DO_NOT_VOTE: "У вас пока нет доступных голосований!",
        VOTES_PAGE_SHOW_VOTE_BTN: "ПОСМОТРЕТЬ",
        VOTES_PAGE_EDIT_VOTE_BTN: "РЕДАКТИРОВАТЬ",
        VOTES_PAGE_DELETE_VOTE_BNT: "УДАЛИТЬ",
        VOTES_PAGE_STATUS_VOTE_WAIT_REG: 'Ожидание регистрации',
        VOTES_PAGE_STATUS_VOTE_PROGRESS_REG: 'Идет регистрация',
        VOTES_PAGE_STATUS_VOTE_WAIT_VOTE: 'Ожидание голосования',
        VOTES_PAGE_STATUS_VOTE_PROGRESS_VOTE: 'Идет голосование',
        VOTES_PAGE_STATUS_VOTE_REG_VOTE: 'Регистрация и голосование',
        VOTES_PAGE_STATUS_VOTE_VOTE_END: 'Голосование завершено',
        VOTES_PAGE_STATUS_VOTE_QUORUM_FAILURE: 'Кворум не достигнут',
        VOTES_PAGE_ALT_ICON_CALENDAR: "иконка календарь",
        VOTES_PAGE_ALT_ICON_TIME: "иконка часы",
        VOTES_PAGE_ALT_ROW_OPEN: "Стрелочка открытия меню",
        VOTES_PAGE_MATERIALS_VOTE: "Материалы голосования"
    },
    ADD_NEW_VOTE: {
        ADD_NEW_VOTE_GENERAL_SETTINGS_TITLE: "Общие настройки",
        ADD_NEW_VOTE_SELECT_ORG_STEP_MOBILE: "Шаг 1: Выбор организации",
        ADD_NEW_VOTE_GENERAL_SETTINGS_TITLE_MOBILE: "Шаг 2: Настройки",
        ADD_NEW_VOTE_QUESTION_TITLE_MOBILE: "Шаг 3: Вопросы",
        ADD_NEW_VOTE_QUESTION_TITLE: "Вопросы",
        ADD_NEW_VOTE_NAME_VOTING: "Название голосования",
        ADD_NEW_VOTE_NAME_VOTING_PLACEHOLDER: "Введите название голосования",
        ADD_NEW_VOTE_CLOSE_VOTING_BTN : "Тайное голосование",
        ADD_NEW_VOTE_OPEN_VOTING_BTN : "Открытое голосование",
        ADD_NEW_VOTE_QUORUM_CONDITION: "Условие кворума",
        ADD_NEW_VOTE_QUORUM_ANY_NUMBERS: "Любое количество",
        ADD_NEW_VOTE_START_REG: "Начало регистрации",
        ADD_NEW_VOTE_END_REG: "Окончание регистрации",
        ADD_NEW_VOTE_START_VOTE: "Начало голосования",
        ADD_NEW_VOTE_END_VOTE: "Окончание голосования",
        START_REG_AND_VOTE: "Начало регистрации и голосования",
        END_REG_AND_VOTE: "Окончание регистрации и голосования",
        ADD_NEW_VOTE_POSSIBLE_CANCEL_ONLINE_REG: "Возможность отмены электронной регистрации",
        ADD_NEW_VOTE_POSSIBLE_CHANGE_VOTE: "Возможность изменения голоса",
        ADD_NEW_VOTE_SETTINGS_USERS: "Настройки пользователей",
        ADD_NEW_VOTE_CLOSE_LISTS: "Закрытые списки",
        ADD_NEW_VOTE_OPEN_LISTS: "Открытые списки",
        ADD_NEW_VOTE_ADD_GROUP_BTN: "Добавить из группы",
        ADD_NEW_VOTE_ADD_USERS_BTN: "Добавить из списка",
        ADD_NEW_VOTE_GROUP_USERS: "Список групп",
        ADD_NEW_VOTE_LIST_USERS: "Список пользователей",
        SELECT_LIST_USERS: "Выберите пользователя из списка",
        SELECT_LIST_GROUP: "Выберите группу из списка",
        ADD_NEW_VOTE_ALLOW_JOIN_LINK_VOTE: "Разрешить другим пользователям присоединяться к голосованию по ссылке",
        ADD_NEW_VOTE_WEIGHT_VOTE: "Весовое голосование",
        ADD_NEW_VOTE_USERNAME_TABLE: "ФИО",
        ADD_NEW_VOTE_WEIGHT_VOTE_TABLE: "Вес голоса",
        ADD_NEW_VOTE_ACTION_TABLE: "Действие",
        ADD_NEW_VOTE_DELETE_BTN_TABLE: "УДАЛИТЬ",
        ADD_NEW_VOTE_MAX_NUMBERS_MEMBERS : "Максимальное количество участников",
        ADD_NEW_VOTE_AFTER_CREATE_VOTE_AVAILABLE_LINK : "После создания голосования вам будет доступна пригласительная ссылка",
        ADD_NEW_VOTE_ADD_QUESTION_BTN: "Добавить вопрос",
        ADD_NEW_VOTE_ADD_ANOTHER_QUESTION_BTN: "ДОБАВИТЬ ЕЩЁ ВОПРОС",
        ADD_NEW_VOTE_SAVE_AS_TEMPLATE_BTN: "Сохранить как черновик",
        ADD_NEW_VOTE_ADD_VOTE_BTN: "Добавить голосование",
        ADD_NEW_VOTE_NEXT_GO_TO_QUESTION_BLOCK: "Далее",
        ADD_NEW_VOTE_ERROR_MESSAGE: "Чтобы создать голосование, добавьте минимум 1 пользователя.",
        ADD_NEW_VOTE_QUESTION_YNQ: "Голосование по вопросу",
        ADD_NEW_VOTE_QUESTION_NONE: "Произвольный вопрос",
        ADD_NEW_VOTE_QUESTION_POSITION_SINGLE: "На позицию (Одна кандидатура)",
        ADD_NEW_VOTE_QUESTION_POSITION_MULTIPLE: "На позицию (Несколько кандидатур)",
        ADD_NEW_VOTE_QUESTION_SAME_POSITIONS: "На несколько позиций (Несколько кандидатур)",
        ADD_NEW_VOTE_QUESTION_GRID: "Сетка",
        ADD_NEW_VOTE_QUESTION_RADIO_GRID: "Радио-сетка",
        QUESTION_TYPE_NAME_QUESTION: "Заголовок вопроса",
        QUESTION_TYPE_VARIANTS_ANSWER: "Варианты ответа",
        QUESTION_TYPE_SELECT_TYPE_QUESTION: "Выберите тип вопроса",
        QUESTION_TYPE_VARIANTS_ANSWER_PLACEHOLDER_ENTER_VARIANT: "Введите вариант ответа",
        QUESTION_TYPE_VARIANTS_ANSWER_PLACEHOLDER_USERNAME: "ФИО претендента",
        QUESTION_TYPE_NAME_QUESTION_PLACEHOLDER_ENTER_YOUR_QUESTION: "Введите ваш вопрос",
        QUESTION_TYPE_NAME_QUESTION_PLACEHOLDER_SELECTION_POSITION: "Отбор на позицию профессора",
        QUESTION_TYPE_NAME_QUESTION_PLACEHOLDER_NUMBER_OF_POSITIONS: "Количество должностных позиций",
        QUESTION_TYPE_GRID_ROWS: "Строки",
        QUESTION_TYPE_GRID_COLUMNS: "Столбцы",
        QUESTION_TYPE_GRID_ENTER_VALUES: "Введите значение",
        QUESTION_TYPE_GRID_NOTE: "Все строки обязательны для заполнения",
        QUESTION_TYPE_RULES_TITLE: "ДОБАВИТЬ ПРАВИЛО",
        QUESTION_TYPE_RULES: "Правило",
        QUESTION_TYPE_RULES_SELECT_CHOOSE_EXACTLY: "Выбрать ровно",
        QUESTION_TYPE_RULES_SELECT_CHOOSE_LESS_THAN: "Выбрать меньше чем",
        QUESTION_TYPE_RULES_SELECT_CHOOSE_MORE_THAN: "Выбрать больше чем",
        QUESTION_TYPE_RULES_SELECT_CHOOSE_LESS_OR_EXACTLY: "Выбрать меньше или ровно",
        QUESTION_TYPE_RULES_SELECT_CHOOSE_MORE_OR_EXACTLY: "Выбрать больше или ровно",
        QUESTION_TYPE_RULES_SELECT_SELECT_INTERVAL_FROM: "Выбрать интервал от",
        QUESTION_TYPE_RULES_SELECT_SELECT_INTERVAL_BEFORE: "До",
        QUESTION_TYPE_RULES_SELECT_SELECT_INTERVAL_ANSWER_OPTIONS: "вариантов ответов",
        QUESTION_TYPE_ADD_QUESTION_BTN: "Добавить вопрос",
        ADD_MATERIALS_VOTE_TITLE: "Добавить материалы к голосованию",
        ADD_MATERIALS_VOTE_TITLE_QUESTION_TYPE: "Добавить материалы к вопросу",
        ADD_MATERIALS_VOTE_PLACEHOLDER: "Заголовок вспомогательного материала",
        ADD_MATERIALS_VOTE_DOCUMENT: "Документ",
        ADD_MATERIALS_VOTE_LINK: "Ссылка",
        ADD_MATERIALS_SUCCESS_INFO: "Готово!",
        EXPAND_LIST_TITLE: "РАСШИРИТЬ СПИСОК",
        EXPAND_LIST_MAIL_ADDRESSES_USERS: "Почтовые адреса пользователей",
        EXPAND_LIST_NOTE: "(по одному на каждую строчку для каждого пользователя)",
        EXPAND_LIST_SEARCH_USERS_BTN: "Найти в базе пользователей",
        EXPAND_LIST_IMPORT_EXCEL: "ИМОРТ ДАННЫХ ИЗ EXCEL",
        CREATED_QUESTION_EDIT_BTN: "РЕДАКТИРОВАТЬ",
        CREATED_QUESTION_DELETE_BTN: "УДАЛИТЬ",
        ADD_OBSERVERS_TITLE_OBSERVER: "ДОБАВИТЬ НАБЛЮДАТЕЛЕЙ",
        ADD_OBSERVERS_TITLE_COUNTING_MEMBERS: "ДОБАВИТЬ ЧЛЕНОВ СЧЕТНОЙ КОМИССИИ",
        ADD_TEMPLATES_NAME_TEMPLATE: "Название шаблона",
        ADD_TEMPLATES_NAME_TEMPLATE_PLACEHOLDER: "Введите название шаблона",
        ADD_TEMPLATES_SAVE_TEMPLATE_BTN: "Сохранить шаблон",
        SELECT_ORG: 'Выберите организацию',
        EVENT_NAME_ERR: 'Отсутствует наименование голосования',
        COMPARE_RS_RE: 'Окончание регистрации не может предшествовать началу регистрации',
        COMPARE_ES_EE: 'Окончание голосования не может предшествовать началу голосования',
        COMPARE_RE_EE: 'Окончание голосования не может предшествовать окончанию регистрации',
        COMPARE_EE_RS: 'Окончание голосования не может предшествовать началу регистрации',
        COMPARE_ES_RS: 'Начало голосования не может предшествовать началу регистрации',
        SKIP_REG: 'Исключить этап регистрации',
        EVENT_MATERIALS_ERR: 'Некорректно заполнены материалы к голосованию',
        QUESTION_MATERIALS_ERR: 'Некорректно заполнены материалы',
        VOTERS_ERR: 'Список голосующих пуст',
        USERS_IN_GROUP: 'Количество участников',
        NO_GROUPS: 'Нет групп для выбора',
        BUTTON_ADD: 'Добавить',
        VOTERS_EXPANDABLE_ERR: 'Максимальное количество участников заполнено некорректно',
        FOR: 'За',
        AGAINST: 'Против',
        ABSTAIN: 'Воздержаться',
        QUESTION_TITLE_ERROR: 'Заполните заголовок вопроса',
        QUESTION: 'Вопрос',
        QUESTIONS_ERR: 'Нет добавленных вопросов',
    },
    ORG_SETTINGS: {
        PLACEHOLDER: 'Введите название компании',
        BUTTON_SAVE: 'Сохранить',
        BUTTON_SAVE_NEW_ADMINS: 'Добавить пользователей',
        BUTTON_CANCEL: 'Отменить',
        ADMINS_LIST: 'Список секретарей',
        GENERAL_SETTINGS: 'Общие настройки',
        PROTOCOL_SETTINGS: 'Настройки протокола подсчета голосов',
        VOTE_CONSTRUCOR: 'Конструктор создания голосования',
        MAILING_SETTINGS: 'Управление рассылкой',
        SUBSCRIPTION_SETTINGS: 'Подписка',
        SETTINGS_BACK: 'К меню настроек',
        ADD_ADMIN: 'добавить администратора',
        BUTTON_SAVE_ADMINS_CHANGE: 'Сохранить изменения',
        BUTTON_LOADING: 'Загрузка...',
        ADD_OBSERVERS: 'Добавить наблюдателей',
        ADD_COUNTERS: 'Добавить счетную комиссию',
        ADD_TEMPLATES: 'Добавить шаблоны голосований',
        INVALID_BALLOTS: 'Разрешить отправку недействительных бюллетеней',
        PROLONG: 'Разрешить продление времени голосования',
        STATISTIC: 'Частота обновления статистики',
        MINUTES: 'минут',
        TIME_ZONE: 'Временная зона',
        SUPPORT_EMAIL: 'E-mail службы поддержки',
        SUPPORT_EMAIL_PLACEGOLDER: 'Введите E-mail службы поддержки',
        DESCRIPTION: 'Примечание',
        DESCRIPTION_PLACEGOLDER: 'Введите примечание',
        BLOCK_ORG: 'Заблокировать организацию',
        UNLOCK_ORG: 'Разблокировать организацию',
        DELETE_ORG: 'Удалить организацию',
        FORM_PROTOCOL: 'Формировать протокол подсчета голосов для завершенных голосований',
        CURRENT_PROTOCOL: 'Используемый шаблон протокола',
        DOWNLOAD_NEW_TEMPLATE_PROTOCOL: 'Загрузить новый шаблон протокола',
        LOAD_BUTTON: 'Загрузить',
        LOAD_READY: 'Готово',
        VOTE_TYPE: 'Отображать элемент выбора типа голосования',
        QUORUM: 'Отображать элемент выбора условия кворума',
        CANCEL_REG: 'Отображать элемент возможности отмены регистрации',
        CHANGE_VOTE: 'Отображать элемент изменения голоса',
        COMBINE_TIME: 'Совместить временные интервалы фазы регистрации и голосования',
        DEFAULT_STATE: 'Выберите значение по умолчанию',
        SECRET_VOTE: 'Тайное голосование',
        OPEN_VOTE: 'Открытое голосование',
        QUORUM_ANY_VALUE: 'Любое количество',
        ALLOW: 'Разрешить',
        PROHIBIT: 'Запретить',
        STANDART_ALERTS: 'Стандартные оповещения',
        CREATE_VOTE: 'О создании голосования',
        START_VOTE: 'О начале голосования',
        END_VOTE: 'Об окончании голосования',
        START_REG: 'О начале регистрации',
        END_REG: 'Об окончании регистрации',
        INTERIM_ALERTS: 'Промежуточные оповещения',
        AFTER_START: 'После начала голосования',
        BEFORE_END: 'Перед окончанием голосования',
        MINUTE: 'минут',
        SAVE_NOTIFICATION_ERROR: 'Необходимо заполнить все поля оповещений',
        ADD_NOTIFICATION: 'добавить оповещение',
        DATE_START: 'Начало подписки',
        DATE_END: 'Окончание подписки',
        DATE_FROM: 'с',
        DATE_TO: 'по',
        VOTERS_LIMIT: 'Количество пользователей',
        EVENTS_LIMIT: 'Количество голосований',
        MESSAGE_CHECKBOX: 'Отправка сообщений',
        MESSAGE_INPUT: 'Доступное количество сообщений',
    },
    ADD_TEMPLATES: {
        ADD_TEMPLATES_NAME_TEMPLATE: "Название шаблона",
        ADD_TEMPLATES_DATE_CREATE: "Дата создания",
        ADD_TEMPLATES_DATE_CREATE_MOBILE: "Дата создания:",
        ADD_TEMPLATES_ACTION: "Действия",
        ADD_TEMPLATES_ADD_TEMPLATE_BTN: "Добавить шаблон",
        ADD_TEMPLATES_SHOW_MORE_BTN: "ПОКАЗАТЬ ПОЛНОСТЬЮ",
        ADD_TEMPLATES_EDIT_MOBILE_BTN: "Редактировать",
        ADD_TEMPLATES_DELETE_MOBILE_BTN: "Удалить"
    },
    DETAILS_VOTE: {
        INFORMATION_MENU_GENERAL_INFO: "Общая информация",
        INFORMATION_MENU_STATISTIC_VOTE: "Статистика голосования",
        INFORMATION_MENU_VOTING: "Голосующие",
        INFORMATION_MENU_OBSERVERS: "Наблюдатели",
        INFORMATION_MENU_KNOW_QUESTIONS: "Ознакомиться с вопросами",
        INFORMATION_MENU_ROW_BACK: "Назад к списку голосований",
        GENERAL_INFO_TITLE: "Общая информация",
        GENERAL_INFO_STATUS_VOTING_IN_PROGRESS: "Идет голосование",
        GENERAL_INFO_STATUS_WAITING_FOR_VOTE: "Ожидание голосования",
        GENERAL_INFO_STATUS_WAITING_FOR_REG: "Ожидание регистрации",
        GENERAL_INFO_STATUS_REG_IN_PROGRESS: "Идет регистрация",
        GENERAL_INFO_STATUS_VOTING_END: "Голосование завершено",
        GENERAL_INFO_STATUS_QUORUM_NOT_REACHED: "Кворум не достигнут",
        GENERAL_INFO_STATUS_REG_AND_VOTE: "Регистрация и голосование",
        GENERAL_INFO_TYPE_VOTE_OPEN: "Открытое",
        GENERAL_INFO_TYPE_VOTE_CLOSE: "Тайное",
        GENERAL_INFO_POSSIBLE_REVOTING: "Возможность переголосования:",
        GENERAL_INFO_POSSIBLE_CANCEL_REG: "Возможность отмены регистрации:",
        GENERAL_INFO_START_REG: "Начало регистрации:",
        GENERAL_INFO_END_REG: "Конец регистрации:",
        GENERAL_INFO_START_VOTE: "Начало голосования:",
        GENERAL_INFO_END_VOTE: "Конец голосования:",
        GENERAL_INFO_START_VOTE_BTN: "Начать голосование",
        GENERAL_INFO_END_VOTE_BTN: "Завершить голосование",
        GENERAL_INFO_START_REG_BTN: "Начать регистрацию",
        GENERAL_INFO_END_REG_BTN: "Завершить регистрацию",
        GENERAL_INFO_DELETE_VOTE_BTN: "Удалить голосование",
        STATISTICS_TITLE_MOBILE: "Статистика",
        STATISTIC_TITLE: "Ход регистрации",
        STATISTIC_LATEST_UPDATE: "Последнее обновление:",
        STATISTIC_REGISTRED_MEMBERS: "Зарегистрированы",
        STATISTIC_NOT_REGISTRED_MEMBERS: "Не зарегестрированы",
        STATISTIC_VOTED: "Проголосовали",
        STATISTIC_NOT_VOTED: "Не проголосовали",
        STATISTIC_REG_GENERAL_MEMBERS: "Зарегестрировано",
        STATISTIC_QUORUM_CONDITION: "Условие кворума",
        STATISTIC_STATUS_EVENT: "Статус события",
        STATISTIC_QUORUM_SUCCESS: "Кворум достигнут",
        STATISTIC_QUORUM_NOT_SUCCESS: "Кворум достигнут",
        STATISTIC_ELECTRONIC_VISIT: "Электронная явка",
        STATISTIC_SHOW_MORE_BTN: "ПОКАЗАТЬ ПОЛНОСТЬЮ",
        STATISTIC_DYNAMIC_VISIT: "Динамика явки",
        STATISTIC_GENERAL_VISIT: "Общая явка",
        STATISTIC_VISIT_VOTING: "Явка голосующих",
        STATISTIC_TABLE_TIME: "Время",
        STATISTIC_TABLE_VISIT_TIME: "Явка за время",
        STATISTIC_HIDE_BTN: "СВЕРНУТЬ",
        VOTING_TITLE: "Список голосующих",
        VOTING_TITLE_MOBILE: "Голосующие",
        VOTING_EXPORT_EXCEL: "ЭКСПОРТ В EXCEL",
        VOTING_STATUS_REGISTRED: "Зарегистрирован",
        VOTING_STATUS_NO_REGISTRED: "Не зарегистрирован",
        VOTING_STATUS_VOTED: "Проголосовал",
        VOTING_STATUS_NO_VOTED: "Не проголосовал",
        VOTING_EMPTY_INFO: "Кажется, в этом голосовании не участвовали наблюдатели! Если вы хотите, чтобы в следующем голосовании были наблюдатели, пожалуйста, добавьте их на этапе",
        VOTING_EMPTY_INFO_LINK: "создания голосования.",
        OBSERVERS_TITLE: "Список наблюдателей",
        OBSERVERS_TITLE_MOBILE: "Наблюдатели",
        COUNTING_TITLE: "Счетная комиссия",
        COUNTING_TITLE_MOBILE: "Наблюдатели",
        COUNTING_STATUS_SIGNED: "Подписал",
        COUNTING_STATUS_NO_SIGNED: "Не подписал",
        QUESTIONS_TITLE: "Вопросы для голосования",
        QUESTIONS_TITLE_MOBILE: "Ознакомиться с вопросами"
    },
    GENERAL: {
        ALT_ICON: "Иконка"
    }
}
