export const constants = {
    AUTH: {
        AUTH_TITLE: "Авторизация",
        AUTH_LABEL_SELECT_ROLE: "Войти как",
        AUTH_LOGIN: "Имя пользователя",
        AUTH_PASS: "Пароль",
        AUTH_FORGET_PASS: "Забыли пароль?",
        AUTH_REMEMBER_ME: "Запомнить меня",
        AUTH_ENTER_BTN: "Войти",
        AUTH_ENTER_LINK_GOSUSLUGI: "Войти через ЕСИА",
        AUTH_TITLE_LOGO_BLOCK: "Панель управления системой электронных голосований",
        AUTH_QUESTION_ACCOUNT: "Еще нет аккаунта?",
        AUTH_REG_BTN: "Зарегистрироваться",
        AUTH_ERROR_MESSAGE: "Неверно введено имя пользователя или пароль"
    },
    AUTH_FORGET_PASS: {
        AUTH_FORGET_PASS_TITLE: "Забыли пароль?",
        AUTH_FORGET_PASS_NOTE: "Пожалуйста, укажите e-mail, который Вы использовали для входа в личный кабинет, и мы пришлем Вам ссылку для смены пароля.",
        AUTH_FORGET_PASS_BTN: "Отправить",
        AUTH_FORGET_PASS_LOGO_TITLE: "Панель управления системой электронных голосований",
        AUTH_FORGET_PASS_ERROR: "Поле заполнено некорректно",
        AUTH_FORGET_PASS_MODAL_TITLE: "Почти готово!",
        AUTH_FORGET_PASS_MODAL_INFO: "На вашу электронную почту отправлена инструкция по смене пароля",
        AUTH_FORGET_PASS_MODAL_BTN: "На страницу входа"
    },
    AUTH_SET_PASS: {
        AUTH_SET_PASS_TITLE: "Установка пароля",
        AUTH_SET_PASS_NEW_PASS: "Новый пароль",
        AUTH_SET_PASS_REPEAT_PASS: "Повторите новый пароль",
        AUTH_SET_PASS_SAVE_BTN: "Сохранить",
        AUTH_SET_PASS_ERROR: "Пароли не совпадают",
        AUTH_SET_PASS_LOGO_TITLE: "Панель управления системой электронных голосований",
        AUTH_SET_PASS_MODAL_INFO: "Ваш пароль успешно изменен!",
        AUTH_SET_PASS_MODAL_BTN: "На страницу входа"
    },
    REG: {
        REG_TITLE: "Регистрация",
        REG_SECOND_NAME: "Фамилия",
        REG_FIRST_NAME: "Имя",
        REG_MIDDLE_NAME: "Отчество",
        REG_EMAIL: "E-mail",
        REG_SET_PASS: "Придумайте пароль",
        REG_REPEAT_PASS: "Повторите пароль",
        REG_SELECT_TIMEZONE: "Выберите часовой пояс",
        REG_POLITIC_INFO_PART1: "Ознакомлен с",
        REG_POLITIC_INFO_PART2: "Подтверждаю принадлежность мне указанного электронного адреса",
        REG_POLITIC_LINK: "Политикой",
        REG_REG_BTN: "Зарегистрироваться",
        REG_TITLE_LOGO_BLOCK: "Панель управления системой электронных голосований",
        REG_QUESTION_ACCOUNT: "Уже есть аккаунт?",
        REG_ENTER_BTN: "Войти",
        REG_STEP_MOBILE: "Шаг 1 из 2",
        REG_ALMOST_READY_MOBILE: "Шаг 2 из 2, почти готово!",
        REG_NEXT_PAGE_MOBILE: "Продолжить",
        REG_ERROR_USERNAME: "Поля “Имя” или “Фамилия” заполнены некорректно",
        REG_ERROR_EMAIL: "Неверный формат почты",
        REG_ERROR_PASS: "Пароли не совпадают",
        REG_ERROR_TIMEZONE: "Выберите часовой пояс"
    },
    REG_COMPLETE_MODAL: {
        REG_COMPLETE_MODAL_INFO: "Вы успешно прошли регистрацию!",
        REG_COMPLETE_MODAL_BTN: "На главную",
        REG_COMPLETE_MODAL_TITLE: "Регистрация"
    },
    HEADER: {
        HEADER_ORG: "Организации",
        HEADER_ADD_BTN: "Добавить",
        HEADER_ADD_ORG: "Организацию",
        HEADER_MYPROFILE_MODAL: "Мой профиль",
        HEADER_MYPROFILE_MODAI_EXIT: "Выйти",
        HEADER_BURGER_ADD_BTN: "Добавить",
        HEADER_BURGER_ORG: "Организации",
        HEADER_BURGER_ADD_ORG: "Организацию",
        HEADER_BURGER_POLITIC: "Политика конфидициальности",
        HEADER_BURGER_EXIT: "Выйти"
    },
    FOOTER: {
        FOOTER_COPI_INFO_PART1: "Система",
        FOOTER_COPI_INFO_PART2: "разработана Центром",
        FOOTER_COPI_INFO_PART3: "технологий распределенных",
        FOOTER_COPI_INFO_PART4: "реестров СПбГУ.",
        FOOTER_COPI_INFO_PART5: "Все права защищены.",
        FOOTER_MAP_SITE: "Карта сайта",
        FOOTER_MAIN_PAGE: "Главная",
        FOOTER_VOTES: "Голосования",
        FOOTER_USERS: "Пользователи",
        FOOTER_ORG: "Организации",
        FOOTER_SETTINGS: "Настройки",
        FOOTER_LANG: "Язык",
        FOOTER_SELECT_LANG_RU: "Русский",
        FOOTER_SELECT_LANG_EN: "Английский",
        FOOTER_SIZE_FONT: "Размер шрифта",
        FOOTER_SELECT_SIZE: "Стандартный",
        FOOTER_TIME_ZONE: "Часовой пояс",
        FOOTER_SELECT_TIME_ZONE: "GMT+03:00",
        FOOTER_SUPPORT: "Поддержка",
        FOOTER_POLITIC: "Политика конфиденциальности",
        FOOTER_MAIL_SUPPORT: "support@dltc.spbu.ru"
    },
    GENERAL_TITLE: {
        GENERAL_TITLE_TITLENAME_ORG: "Список организаций",
        GENERAL_TITLE_FIRTSLETTER: "АдминистраторКриптовече",
        GENERAL_TITLE_SECONDLETTER_ORG: "Организация",
        GENERAL_TITLE_TITLENAME_ADD_ORG: "Добавление новой организации",
        GENERAL_TITLE_SECONDLETTER_GROUP_USERS: "Группы пользователей",
        GENERAL_TITLE_TITLENAME_PROFILE: "Профиль пользователя"
    },
    SORTING_BLOCK: {
        SORTING_BLOCK_LABEL: "Сортировать по:",
        SORTING_BLOCK_TYPE_SORT: "Количеству транзакций"
    },
    PAGINATION: {
        PAGINATION_SHOW_LABEL: "Показать",
        PAGINATION_PAGE_FROM_PAGE: "из",
        PAGINATION_SEARCH: "Поиск"
    },
    ORGANIZATIONS_LIST: {
        ORGANIZATIONS_LIST_NAME_ORG: "Название организации",
        ORGANIZATIONS_LIST_SECRETARY: "Секретари",
        ORGANIZATIONS_LIST_GROUP_USERS: "Группы пользователей",
        ORGANIZATIONS_LIST_VOTES: "Голосования",
        ORGANIZATIONS_LIST_ACTIVE_VOTES: "Активные голосования",
        ORGANIZATIONS_LIST_TEMPLATES: "Шаблоны",
        ORGANIZATIONS_LIST_ACTIONS: "Действия",
        ORGANIZATIONS_LIST_EDIT_BTN: "РЕДАКТИРОВАТЬ",
        ORGANIZATIONS_LIST_EDIT_BTN_MOBILE: "Редактировать"
    },
    ADD_NEW_ORG: {
        ADD_NEW_ORG_NAME_ORG: "Название организации",
        ADD_NEW_ORG_PLACEHOLDER_NAME: "Введите название организации",
        ADD_NEW_ORG_IMPORT_EXCEL_BTN: "Импорт пользователей из Excel",
        ADD_NEW_ORG_ADD_USERS_MAIL_BTN: "Добавить пользователей по E-mail",
        ADD_NEW_ORG_ADD_USERS_MAIL_BTN_MOBILE: "Добавить пользователей",
        ADD_NEW_ORG_MAIL_ADDRESS_USERS: "Почтовые адреса пользователей",
        ADD_NEW_ORG_MAIL_ADDRESS_USERS_RULE: "(по одному на каждую строчку для каждого пользователя)",
        ADD_NEW_ORG_SEARCH_USERS_BASE_BTN: "Найти в базе пользователей",
        ADD_NEW_ORG_E_MAIL_SUPPORT: "E-mail поддержки",
        ADD_NEW_ORG_E_MAIL_SUPPORT_PLACEHOLDER: "Введите E-mail поддержки",
        ADD_NEW_ORG_NOTE: "Примечание",
        ADD_NEW_ORG_INPUT_NOTE: "Введите примечание",
        ADD_NEW_ORG_SAVE_BTN: "Сохранить",
        ADD_NEW_ORG_SUPERUSER: "Суперпользователь",
        ADD_NEW_ORG_DELETE_BTN: "УДАЛИТЬ",
        ADD_NEW_ORG_DELETE_BTN_MOBILE: "Удалить",
        ADD_NEW_ORG_BLOCK_BTN: "Заблокировать",
        ADD_NEW_ORG_UNBLOCK_BTN: "Разблокировать",
        ADD_NEW_ORG_SHOW_MORE_BTN: "ПОКАЗАТЬ ЕЩЁ"
    },
    PROFILE_USER: {
        PROFILE_USER_EDIT_BTN: "Редактировать профиль",
        PROFILE_USER_ORG_GROUP_USERS: "Организации и группы пользователя",
        PROFILE_USER_VOTES: "Голосования",
        PROFILE_USER_STATUS_VOTING: "Голосующий",
        PROFILE_USER_STATUS_OBSERVER: "Наблюдатель",
        PROFILE_USER_STATUS_SECRETARY: "Секретарь",
        PROFILE_USER_SHOW_ALL: "ПОКАЗАТЬ ПОЛНОСТЬЮ",
        PROFILE_USER_SAVE_BTN: "Сохранить изменения",
        PROFILE_USER_CHANGE_PERSONAL_DATA: "Изменить личные данные",
        PROFILE_USER_SURNAME: "Фамилия",
        PROFILE_USER_NAME: "Имя",
        PROFILE_USER_MIDDLE_NAME: "Отчество",
        PROFILE_USER_CHANGE_TIMEZONE: "Изменить часовой пояс",
        PROFILE_USER_CHANGE_PASS: "Изменить пароль",
        PROFILE_USER_PASS: "Пароль",
        PROFILE_USER_NEW_PASS: "Новый пароль",
        PROFILE_USER_REPEAT_PASS: "Повторите новый пароль"
    }
}
