export const constants = {
    AUTH: {
        AUTH_TITLE: "Авторизация",
        AUTH_LABEL_SELECT_ROLE: "Войти как",
        AUTH_LOGIN: "Имя пользователя",
        AUTH_PASS: "Пароль",
        AUTH_PASS_PLACEHOLDER: "Введите пароль",
        AUTH_FORGET_PASS: "Забыли пароль?",
        AUTH_REMEMBER_ME: "Запомнить меня",
        AUTH_ENTER_BTN: "Войти",
        AUTH_ENTER_BTN_LOADING: "Загрузка...",
        AUTH_ENTER_LINK_GOSUSLUGI: "Войти через ЕСИА",
        AUTH_TITLE_LOGO_BLOCK: "Панель управления системой электронных голосований",
        AUTH_QUESTION_ACCOUNT: "Еще нет аккаунта?",
        AUTH_REG_BTN: "Зарегистрироваться",
        AUTH_ERROR_MESSAGE: "Неверно введено имя пользователя или пароль",
        AUTH_ERROR_MESSAGE_REQUIRED: "Заполните все обязательные поля",
        AUTH_ROLE_ADMIN: 'Секретарь',
        AUTH_ROLE_OBSERVER: 'Наблюдатель',
        AUTH_ROLE_COUNTER: 'Член счетной комиссии'
    },
    HEADER: {
        HEADER_ORG: "Организации",
        HEADER_MAIN: "Главная",
        HEADER_USERS: "Пользователи",
        HEADER_VOTE: "Голосования",
        HEADER_GROUP_USERS: "Группы пользователей",
        HEADER_USERS_LIST: "Список пользователей",
        HEADER_LIST_VOTES: "Список голосований",
        HEADER_TEMPLATE_VOTES: "Шаблоны голосований",
        HEADER_ADD_BTN: "Добавить",
        HEADER_ADD_ORG: "Организацию",
        HEADER_ADD_VOTE: "Голосование",
        HEADER_ADD_TEMPLATE_VOTE: "Шаблон голосования",
        HEADER_ADD_GROUP_USERS: "Группу пользователей",
        HEADER_MYPROFILE_MODAL: "Мой профиль",
        HEADER_MYPROFILE_MODAI_EXIT: "Выйти",
        HEADER_BURGER_ADD_BTN: "Добавить",
        HEADER_BURGER_ORG: "Организации",
        HEADER_BURGER_ADD_ORG: "Организацию",
        HEADER_BURGER_POLITIC: "Политика конфидициальности",
        HEADER_BURGER_EXIT: "Выйти"
    },
    FOOTER: {
        FOOTER_COPI_INFO_PART1: "Система",
        FOOTER_COPI_INFO_PART2: "разработана Центром",
        FOOTER_COPI_INFO_PART3: "технологий распределенных",
        FOOTER_COPI_INFO_PART4: "реестров СПбГУ.",
        FOOTER_COPI_INFO_PART5: "Все права защищены.",
        FOOTER_MAP_SITE: "Карта сайта",
        FOOTER_MAIN_PAGE: "Главная",
        FOOTER_VOTES: "Голосования",
        FOOTER_LIST_VOTES: "Список голосований",
        FOOTER_TEMPLATE_VOTES: "Шаблоны голосований",
        FOOTER_USERS: "Пользователи",
        FOOTER_GROUP_USERS: "Группы пользователей",
        FOOTER_LIST_USERS: "Список пользователей",
        FOOTER_ORG: "Организации",
        FOOTER_MYPROFILE: "Мой профиль",
        FOOTER_SETTINGS: "Настройки",
        FOOTER_LANG: "Язык",
        FOOTER_SELECT_LANG_RU: "Русский",
        FOOTER_SELECT_LANG_EN: "Английский",
        FOOTER_SIZE_FONT: "Размер шрифта",
        FOOTER_SELECT_SIZE: "Стандартный",
        FOOTER_TIME_ZONE: "Часовой пояс",
        FOOTER_SELECT_TIME_ZONE: "GMT+03:00",
        FOOTER_SUPPORT: "Поддержка",
        FOOTER_POLITIC: "Политика конфиденциальности",
        FOOTER_MAIL_SUPPORT: "support@dltc.spbu.ru"
    },
    GENERAL_TITLE: {
        GENERAL_TITLE_TITLENAME_ORG: "Список организаций",
        GENERAL_TITLE_TITLENAME_GROUP_USER: "Группы пользователей",
        GENERAL_TITLE_TITLENAME_ADD_ORG: "Добавление новой организации",
        GENERAL_TITLE_TITLENAME_ADD_GROUP_USERS: "Добавление группы пользователей",
        GENERAL_TITLE_TITLENAME_LIST_USERS: "Список пользователей",
        GENERAL_TITLE_TITLENAME_PROFILE: "Профиль пользователя",
        GENERAL_TITLE_FIRTSLETTER: "АдминистраторКриптовече",
        GENERAL_TITLE_SECONDLETTER_ORG: "Организация",
        GENERAL_TITLE_SECONDLETTER_GROUP_USERS: "Группы пользователей",
        GENERAL_TITLE_SECONDLETTER_LIST_USERS: "Список пользователей"
    },
    SORTING_BLOCK: {
        SORTING_BLOCK_LABEL: "Сортировать по:",
        SORTING_BLOCK_TYPE_SORT: "Количеству транзакций",
        SORTING_BLOCK_FILTER_BTN: "Фильтры",
        SORTING_BLOCK_SORT_BTN: "Сортировка"
    },
    PAGINATION: {
        PAGINATION_SHOW_LABEL: "Показать",
        PAGINATION_PAGE_FROM_PAGE: "из",
        PAGINATION_SEARCH: "Поиск"
    },
    ORGANIZATIONS_LIST: {
        ORGANIZATIONS_LIST_NAME_ORG: "Название организации",
        ORGANIZATIONS_LIST_SECRETARY: "Секретари",
        ORGANIZATIONS_LIST_GROUP_USERS: "Группы пользователей",
        ORGANIZATIONS_LIST_VOTES: "Голосования",
        ORGANIZATIONS_LIST_ACTIVE_VOTES: "Активные голосования",
        ORGANIZATIONS_LIST_TEMPLATES: "Шаблоны",
        ORGANIZATIONS_LIST_ACTIONS: "Действия",
        ORGANIZATIONS_LIST_EDIT_BTN: "РЕДАКТИРОВАТЬ",
        ORGANIZATIONS_LIST_EDIT_BTN_MOBILE: "Редактировать"
    },
    ADD_NEW_ORG: {
        ADD_NEW_ORG_NAME_ORG: "Название организации",
        ADD_NEW_ORG_PLACEHOLDER_NAME: "Введите название организации",
        ADD_NEW_ORG_IMPORT_EXCEL_BTN: "Импорт пользователей из Excel",
        ADD_NEW_ORG_ADD_USERS_MAIL_BTN: "Добавить пользователей по E-mail",
        ADD_NEW_ORG_ADD_USERS_MAIL_BTN_MOBILE: "Добавить пользователей",
        ADD_NEW_ORG_MAIL_ADDRESS_USERS: "Почтовые адреса пользователей",
        ADD_NEW_ORG_DOWNLOAD_FILE_LABEL: "Загрузить xls/xlsx документ со списком пользователей",
        ADD_NEW_ORG_LOAD_BTN: "Загрузить",
        ADD_NEW_ORG_SUCCESS_INFO: "Файл успешно загружен",
        ADD_NEW_ORG_MAIL_ADDRESS_USERS_RULE: "(по одному на каждую строчку для каждого пользователя)",
        ADD_NEW_ORG_SEARCH_USERS_BASE_BTN: "Найти в базе пользователей",
        ADD_NEW_ORG_E_MAIL_SUPPORT: "E-mail поддержки",
        ADD_NEW_ORG_E_MAIL_SUPPORT_PLACEHOLDER: "Введите E-mail поддержки",
        ADD_NEW_ORG_NOTE: "Примечание",
        ADD_NEW_ORG_INPUT_NOTE: "Введите примечание",
        ADD_NEW_ORG_SAVE_BTN: "Сохранить",
        ADD_NEW_ORG_SUPERUSER: "Суперпользователь",
        ADD_NEW_ORG_DELETE_BTN: "УДАЛИТЬ",
        ADD_NEW_ORG_DELETE_BTN_MOBILE: "Удалить",
        ADD_NEW_ORG_BLOCK_BTN: "Заблокировать",
        ADD_NEW_ORG_UNBLOCK_BTN: "Разблокировать",
        ADD_NEW_ORG_SHOW_MORE_BTN: "ПОКАЗАТЬ ЕЩЁ"
    },
    ADD_NEW_GROUP_USERS: {
        ADD_NEW_GROUP_USERS_SELECT_ORG: "Выбор организации",
        ADD_NEW_GROUP_USERS_ORG: "Организация",
        ADD_NEW_GROUP_NEXT_BTN: "Далее",
        ADD_NEW_GROUP_USERS_NAME_GROUP_USERS: "Название группы пользователей",
        ADD_NEW_GROUP_USERS_PLACEHOLDER_NAME: "Введите название группы",
        ADD_NEW_GROUP_USERS_IMPORT_EXCEL_BTN: "Импорт пользователей из Excel",
        ADD_NEW_GROUP_USERS_ADD_GROUP_BTN: "Добавить в группу пользователей",
        ADD_NEW_GROUP_MAIL_ADDRESS_USERS: "Почтовые адреса пользователей",
        ADD_NEW_GROUP_MAIL_ADDRESS_USERS_RULE: "(по одному на каждую строчку для каждого пользователя)",
        ADD_NEW_GROUP_SEARCH_USERS_BASE_BTN: "Найти в базе пользователей",
        ADD_NEW_GROUP_USERS_DELETE_BTN: "УДАЛИТЬ",
        ADD_NEW_GROUP_USERS_SAVE_BTN: "Сохранить",
        ADD_NEW_GROUP_USERS_SHOW_MORE_BTN: "ПОКАЗАТЬ ЕЩЁ",
        ADD_NEW_GROUP_USERS_LOAD_BTN: "Загрузить",
        ADD_NEW_GROUP_USERS_DOWNLOAD_FILE_LABEL: "Загрузить xls/xlsx документ со списком пользователей",
        ADD_NEW_GROUP_SUCCESS_INFO: "Файл успешно загружен"
    },
    PROFILE_USER: {
        PROFILE_USER_EDIT_BTN: "Редактировать профиль",
        PROFILE_USER_ORG_GROUP_USERS: "Организации и группы пользователя",
        PROFILE_USER_ACTIVITY_IN_USER_GROUPS: "Членство в группах пользователей",
        PROFILE_USER_VOTES: "Голосования",
        PROFILE_USER_STATUS_VOTING: "Голосующий",
        PROFILE_USER_STATUS_OBSERVER: "Наблюдатель",
        PROFILE_USER_STATUS_SECRETARY: "Секретарь",
        PROFILE_USER_SHOW_ALL: "ПОКАЗАТЬ ПОЛНОСТЬЮ",
        PROFILE_USER_SAVE_BTN: "Сохранить изменения",
        PROFILE_USER_CHANGE_PERSONAL_DATA: "Изменить личные данные",
        PROFILE_USER_SURNAME: "Фамилия",
        PROFILE_USER_NAME: "Имя",
        PROFILE_USER_MIDDLE_NAME: "Отчество",
        PROFILE_USER_CHANGE_TIMEZONE: "Изменить часовой пояс",
        PROFILE_USER_CHANGE_PASS: "Изменить пароль",
        PROFILE_USER_PASS: "Пароль",
        PROFILE_USER_NEW_PASS: "Новый пароль",
        PROFILE_USER_REPEAT_PASS: "Повторите новый пароль"
    },
    GROUP_USERS: {
        GROUP_USERS_NAME_GROUP_USERS: "Название группы пользователей",
        GROUP_USERS_MEMBERS: "Участники",
        GROUP_USERS_ACTIONS: "Действия",
        GROUP_USERS_EDIT_BTN: "РЕДАКТИРОВАТЬ",
        GROUP_USERS_BLOCK_BTN: "ЗАБЛОКИРОВАТЬ",
        GROUP_USERS_UNBLOCK_BTN: "РАЗБЛОКИРОВАТЬ",
        GROUP_USERS_DELETE_BTN: "УДАЛИТЬ",
        GROUP_USERS_ADD_USER_BTN_MOBILE: "Добавить пользователей",
        GROUP_USERS_SELECT_BTN_SELECT: "Выбрать"
    },
    LIST_USERS: {
        LIST_USERS_TABLE_EMAIL: "E-mail",
        LIST_USERS_USERNAME: "ФИО",
        LIST_USERS_ACTIONS: "Действия",
        LIST_USERS_WATCH_PROFILE: "ПОСМОТРЕТЬ ПРОФИЛЬ",
        LIST_USERS_SHOW_MORE: "ПОКАЗАТЬ ЕЩЁ"
    }
}
